apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pg-pv-volume"
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0cf155bf7e7a48b38
    fsType: ext4
  storageClassName: ""

