apiVersion: v1
kind: Namespace
metadata: 
  name: fargate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-postgres-sample
  namespace: fargate
  name: spring-boot-postgres-sample
spec:
  ports:
    - name: spring-boot-postgres-sample
      port: 8080
      protocol: TCP
  selector:
    app: spring-boot-postgres-sample
  type: LoadBalancer
